version: 2

models:
  - name: victimas_clean
    description: "Tabla refinada con columnas renombradas a snake_case"
    columns:
      - name: origen
        description: "Origen del registro"
      - name: id_persona
        description: "Identificador único de la persona"
      - name: tipo_documento
        description: "Tipo de documento de identidad"
      - name: fecha_nacimiento
        description: "Fecha de nacimiento de la víctima"
