-- Reference to raw data using dbt source
-- Configured as view since it will be under constant load
-- Normalize names of columns: miniscule  and snake_case

SELECT
    ORIGEN AS origen,
    FUENTE AS fuente,
    PROGRAMA AS programa,
    IDPERSONA AS id_persona,
    IDHOGAR AS id_hogar,
    TIPODOCUMENTO AS tipo_documento,
    DOCUMENTO AS documento,
    PRIMERNOMBRE AS primer_nombre,
    SEGUNDONOMBRE AS segundo_nombre,
    PRIMERAPELLIDO AS primer_apellido,
    SEGUNDOAPELLIDO AS segundo_apellido,
    NOMBRECOMPLETO AS nombre_completo,
    FECHANACIMIENTO AS fecha_nacimiento,
    FECHAEXPEDICIONDOCUMENTO AS fecha_expedicion_documento,
    EXPEDICIONDOCUMENTO AS expedicion_documento,
    PERTENENCIAETNICA AS pertenencia_etnica,
    GENERO AS genero,
    TIPOHECHO AS tipo_hecho,
    FECHAOCURRENCIA AS fecha_ocurrencia,
    HECHO AS hecho,
    CODDANEMUNICIPIOOCURRENCIA AS cod_dane_municipio_ocurrencia,
    CODDANEMUNICIPIORESIDENCIA AS cod_dane_municipio_residencia,
    ZONAOCURRENCIA AS zona_ocurrencia,
    UBICACIONOCURRENCIA AS ubicacion_ocurrencia,
    ZONARESIDENCIA AS zona_residencia,
    UBICACIONRESIDENCIA AS ubicacion_residencia,
    DIRECCION AS direccion,
    PRESUNTOACTOR AS presunto_actor,
    PRESUNTOVICTIMIZANTE AS presunto_victimizante,
    TIPOPOBLACION AS tipo_poblacion,
    TIPOVICTIMA AS tipo_victima,
    TIPODESPLAZAMIENTO AS tipo_desplazamiento,
    NUMTELEFONOFIJO AS num_telefono_fijo,
    NUMTELEFONOCELULAR AS num_telefono_celular,
    PAIS AS pais,
    CIUDAD AS ciudad,
    EMAIL AS email,
    ESTADOVICTIMA AS estado_victima,
    CODDANEDECLARACION AS cod_dane_declaracion,
    CODDANELLEGADA AS cod_dane_llegada,
    FEcharEPORTE AS fecha_reporte,
    FECHAVALORACION AS fecha_valoracion,
    IDSINIESTRO AS id_siniestro,
    IDMIJEFE AS id_mi_jefe,
    VIGENCIADOCUMENTO AS vigencia_documento,
    RELACION AS relacion,
    CODIGOHECHO AS codigo_hecho,
    CONSPERSONA AS cons_persona,
    DISCAPACIDAD AS discapacidad,
    DESCRIPCIONDISCAPACIDAD AS descripcion_discapacidad,
    REGISTRADURIA AS registraduria,
    FUD_FICHA AS fud_ficha,
    AFECTACIONES AS afectaciones
FROM {{ source('raw', 'victimas') }}

