version: 2

models:
  - name: stg_victimas
    description: "Tabla staging con datos crudos de víctimas cargados desde CSV"
    columns:
      - name: ORIGEN
        description: "Origen del registro"
      - name: IDPERSONA
        description: "Identificador único de la persona"
